//! WASM client for hotmeal
//!
//! Applies DOM patches in the browser using web-sys.
//! This is used to test that patches generated by hotmeal
//! correctly transform the DOM when applied in a real browser.
//!
//! ## Chawathe Semantics
//!
//! Patches follow Chawathe edit script semantics: Insert and Move operations
//! do NOT shift siblings. Instead, they displace whatever node occupies the
//! target position into a numbered slot. The DOM's `replaceChild` method
//! provides atomic displacement, returning the removed node for storage.

use hotmeal::{InsertContent, NodeId, PropKey, parse};
use tracing::{debug, trace};
use wasm_bindgen::prelude::*;
use web_sys::{Document, Element, Node};

/// Initialize tracing subscriber for WASM (sends output to browser console).
/// Call this once at startup.
#[wasm_bindgen]
pub fn init_tracing() {
    let mut config = wasm_tracing::WasmLayerConfig::default();
    config.set_max_level(tracing::Level::TRACE);
    let _ = wasm_tracing::set_as_global_default_with_config(config);
}

// Re-export patch types for reference
pub use hotmeal::{NodePath, NodeRef, Patch, PropChange};

/// Compute diff between two HTML documents and return patches as JSON.
/// This allows computing diffs in the browser for fuzzing tests.
#[wasm_bindgen]
pub fn diff_html(old_html: &str, new_html: &str) -> Result<String, JsValue> {
    let patches = hotmeal::diff_html(old_html, new_html)
        .map_err(|e| JsValue::from_str(&format!("diff failed: {e}")))?;

    let json = facet_json::to_string(&patches)
        .map_err(|e| JsValue::from_str(&format!("serialize failed: {e}")))?;

    Ok(json)
}

/// Slots for detached nodes during patch application.
/// In Chawathe's model, INSERT doesn't shift - it displaces the occupant to a slot.
struct Slots {
    nodes: Vec<Option<Node>>,
}

impl Slots {
    fn new() -> Self {
        Self { nodes: Vec::new() }
    }

    fn store(&mut self, slot: u32, node: Node) {
        let idx = slot as usize;
        if idx >= self.nodes.len() {
            self.nodes.resize(idx + 1, None);
        }
        self.nodes[idx] = Some(node);
    }

    fn take(&mut self, slot: u32) -> Option<Node> {
        let idx = slot as usize;
        if idx < self.nodes.len() {
            self.nodes[idx].take()
        } else {
            None
        }
    }

    fn get(&self, slot: u32) -> Option<&Node> {
        let idx = slot as usize;
        self.nodes.get(idx).and_then(|n| n.as_ref())
    }
}

/// Apply a list of patches to the current document.
/// Returns the number of patches applied, or an error message.
#[wasm_bindgen]
pub fn apply_patches_json(patches_json: &str) -> Result<usize, JsValue> {
    let patches: Vec<Patch> = facet_json::from_str(patches_json)
        .map_err(|e| JsValue::from_str(&format!("Failed to parse patches: {e}")))?;

    apply_patches(&patches)
}

/// Apply patches to the document.
pub fn apply_patches(patches: &[Patch]) -> Result<usize, JsValue> {
    let window = web_sys::window().ok_or_else(|| JsValue::from_str("no window"))?;
    let document = window
        .document()
        .ok_or_else(|| JsValue::from_str("no document"))?;

    let count = patches.len();
    log(&format!("[hotmeal-wasm] applying {} patches", count));

    let mut slots = Slots::new();

    for (i, patch) in patches.iter().enumerate() {
        log(&format!("[hotmeal-wasm] patch {}: {:?}", i, patch));
        apply_patch(&document, patch, &mut slots).map_err(|e| {
            JsValue::from_str(&format!(
                "patch {}: {}",
                i,
                e.as_string().unwrap_or_default()
            ))
        })?;
    }

    Ok(count)
}

fn apply_patch(doc: &Document, patch: &Patch, slots: &mut Slots) -> Result<(), JsValue> {
    debug!(?patch, "applying patch");
    match patch {
        Patch::SetText { path, text } => {
            let node = find_node(doc, path, slots)?;
            node.set_text_content(Some(text));
        }

        Patch::SetAttribute { path, name, value } => {
            let el = find_element(doc, path, slots)?;
            // Convert QualName to attribute name string
            let attr_name = if let Some(ref prefix) = name.prefix {
                format!("{}:{}", prefix, name.local)
            } else {
                name.local.to_string()
            };
            el.set_attribute(&attr_name, value)?;
        }

        Patch::RemoveAttribute { path, name } => {
            let el = find_element(doc, path, slots)?;
            // Convert QualName to attribute name string
            let attr_name = if let Some(ref prefix) = name.prefix {
                format!("{}:{}", prefix, name.local)
            } else {
                name.local.to_string()
            };
            el.remove_attribute(&attr_name)?;
        }

        Patch::Remove { node } => {
            let NodeRef(path) = node;
            let slot = path.0[0];
            if slot == 0 {
                // Main tree - replace with empty text node (no shifting - Chawathe semantics)
                let rel_path = NodePath(path.0[1..].to_vec());
                let body: Node = doc
                    .body()
                    .ok_or_else(|| JsValue::from_str("no body"))?
                    .into();
                let target = navigate_within_node(&body, &rel_path)?;
                if let Some(parent) = target.parent_node() {
                    let empty_text: Node = doc.create_text_node("").into();
                    parent.replace_child(&empty_text, &target)?;
                }
            } else {
                // Slot - just remove from slots if it's the root, otherwise navigate within
                if path.0.len() == 1 {
                    // Removing the slot root itself
                    slots.take(slot as u32);
                } else {
                    // Removing a child within the slot
                    let slot_root = slots
                        .get(slot as u32)
                        .cloned()
                        .ok_or_else(|| JsValue::from_str(&format!("slot {} is empty", slot)))?;
                    let rel_path = NodePath(path.0[1..].to_vec());
                    let target = navigate_within_node(&slot_root, &rel_path)?;
                    if let Some(parent) = target.parent_node() {
                        let empty_text = doc.create_text_node("");
                        parent.replace_child(&empty_text, &target)?;
                    }
                }
            }
        }

        Patch::InsertElement {
            at,
            tag,
            attrs,
            children,
            detach_to_slot,
        } => {
            // Extract parent and position from NodeRef
            // Path format: [slot, ...rest] where first element is slot number
            let NodeRef(path) = at;
            if path.0.len() < 2 {
                return Err(JsValue::from_str("InsertElement: path too short"));
            }
            let slot = path.0[0];
            let position = path.0[path.0.len() - 1];

            // Get the slot root (body for slot 0, or stored slot node)
            let slot_root: Node = if slot == 0 {
                doc.body()
                    .ok_or_else(|| JsValue::from_str("no body"))?
                    .into()
            } else {
                slots
                    .get(slot as u32)
                    .cloned()
                    .ok_or_else(|| JsValue::from_str(&format!("slot {} is empty", slot)))?
            };

            // Navigate to parent (path minus first element [slot] and last element [position])
            let parent_path = NodePath(path.0[1..path.0.len() - 1].to_vec());
            let parent_node = if parent_path.0.is_empty() {
                slot_root
            } else {
                navigate_within_node(&slot_root, &parent_path)?
            };

            let parent_el = parent_node
                .dyn_ref::<Element>()
                .ok_or_else(|| JsValue::from_str("parent is not an element"))?
                .clone();

            // Create the new element
            let new_el = doc.create_element(tag)?;

            // Set attributes
            for attr in attrs {
                // Convert QualName to attribute name string
                let attr_name = if let Some(ref prefix) = attr.name.prefix {
                    format!("{}:{}", prefix, attr.name.local)
                } else {
                    attr.name.local.to_string()
                };
                new_el.set_attribute(&attr_name, &attr.value)?;
            }

            // Add children
            for child in children {
                let child_node = create_insert_content(doc, child)?;
                new_el.append_child(&child_node)?;
            }

            // Insert at position with Chawathe displacement semantics
            insert_at_position(
                doc,
                &parent_el,
                &new_el.into(),
                position,
                *detach_to_slot,
                slots,
            )?;
        }

        Patch::InsertText {
            at,
            text,
            detach_to_slot,
        } => {
            // Extract parent and position from NodeRef
            // Path format: [slot, ...rest] where first element is slot number
            let NodeRef(path) = at;
            if path.0.len() < 2 {
                return Err(JsValue::from_str("InsertText: path too short"));
            }
            let slot = path.0[0];
            let position = path.0[path.0.len() - 1];

            // Get the slot root (body for slot 0, or stored slot node)
            let slot_root: Node = if slot == 0 {
                doc.body()
                    .ok_or_else(|| JsValue::from_str("no body"))?
                    .into()
            } else {
                slots
                    .get(slot as u32)
                    .cloned()
                    .ok_or_else(|| JsValue::from_str(&format!("slot {} is empty", slot)))?
            };

            // Navigate to parent (path minus first element [slot] and last element [position])
            let parent_path = NodePath(path.0[1..path.0.len() - 1].to_vec());
            let parent_node = if parent_path.0.is_empty() {
                slot_root
            } else {
                navigate_within_node(&slot_root, &parent_path)?
            };

            let parent_el = parent_node
                .dyn_ref::<Element>()
                .ok_or_else(|| JsValue::from_str("parent is not an element"))?
                .clone();

            // Create text node
            let text_node = doc.create_text_node(text);

            // Insert at position with Chawathe displacement semantics
            insert_at_position(
                doc,
                &parent_el,
                &text_node.into(),
                position,
                *detach_to_slot,
                slots,
            )?;
        }

        Patch::InsertComment {
            at,
            text,
            detach_to_slot,
        } => {
            // Extract parent and position from NodeRef
            // Path format: [slot, ...rest] where first element is slot number
            let NodeRef(path) = at;
            if path.0.len() < 2 {
                return Err(JsValue::from_str("InsertComment: path too short"));
            }
            let slot = path.0[0];
            let position = path.0[path.0.len() - 1];

            // Get the slot root (body for slot 0, or stored slot node)
            let slot_root: Node = if slot == 0 {
                doc.body()
                    .ok_or_else(|| JsValue::from_str("no body"))?
                    .into()
            } else {
                slots
                    .get(slot as u32)
                    .cloned()
                    .ok_or_else(|| JsValue::from_str(&format!("slot {} is empty", slot)))?
            };

            // Navigate to parent (path minus first element [slot] and last element [position])
            let parent_path = NodePath(path.0[1..path.0.len() - 1].to_vec());
            let parent_node = if parent_path.0.is_empty() {
                slot_root
            } else {
                navigate_within_node(&slot_root, &parent_path)?
            };

            let parent_el = parent_node
                .dyn_ref::<Element>()
                .ok_or_else(|| JsValue::from_str("parent is not an element"))?
                .clone();

            // Create comment node
            let comment_node = doc.create_comment(text);

            // Insert at position with Chawathe displacement semantics
            insert_at_position(
                doc,
                &parent_el,
                &comment_node.into(),
                position,
                *detach_to_slot,
                slots,
            )?;
        }

        Patch::UpdateProps { path, changes } => {
            let node = find_node(doc, path, slots)?;

            // Handle text content updates
            if let Some(text_change) = changes.iter().find(|c| matches!(c.name, PropKey::Text))
                && let Some(v) = &text_change.value
            {
                node.set_text_content(Some(v));
            }
            // None means keep existing - do nothing

            // Handle element attribute updates
            // The changes vec represents the ENTIRE final attribute state in order
            if let Some(el) = node.dyn_ref::<Element>() {
                // Save existing attribute values (for None = keep existing)
                let existing: std::collections::HashMap<String, String> =
                    (0..el.attributes().length())
                        .filter_map(|i| el.attributes().item(i).map(|a| (a.name(), a.value())))
                        .collect();

                // Remove ALL existing attributes first to preserve order
                for attr_name in existing.keys() {
                    el.remove_attribute(attr_name)?;
                }

                // Re-add attributes in the order specified by changes
                for change in changes {
                    if let PropKey::Attr(ref qual_name) = change.name {
                        let attr_name = if let Some(ref prefix) = qual_name.prefix {
                            format!("{}:{}", prefix, qual_name.local)
                        } else {
                            qual_name.local.to_string()
                        };
                        // Use new value if Some, otherwise keep existing
                        let value = match &change.value {
                            Some(v) => v.as_ref().to_string(),
                            None => existing.get(&attr_name).cloned().unwrap_or_default(),
                        };
                        el.set_attribute(&attr_name, &value)?;
                    }
                }
            }
        }

        Patch::Move {
            from,
            to,
            detach_to_slot,
        } => {
            let from_path = &from.0;
            let to_path = &to.0;

            // Get the node to move
            let node = if from_path.0.len() == 1 {
                // Path of length 1 means [slot] - moving the entire slot root
                let slot = from_path.0[0] as u32;
                slots
                    .take(slot)
                    .ok_or_else(|| JsValue::from_str(&format!("slot {} is empty", slot)))?
            } else {
                // Navigate to the node and detach with placeholder
                let node = find_node(doc, from_path, slots)?;
                if let Some(parent) = node.parent_node() {
                    let empty_text = doc.create_text_node("");
                    parent.replace_child(&empty_text, &node)?;
                }
                node
            };

            // Get parent and position from target path
            if to_path.0.len() < 2 {
                return Err(JsValue::from_str("Move: target path too short"));
            }
            let parent_path = NodePath(to_path.0[..to_path.0.len() - 1].to_vec());
            let target_idx = to_path.0[to_path.0.len() - 1];

            let parent_node = find_node(doc, &parent_path, slots)?;
            let parent_el = parent_node
                .dyn_ref::<Element>()
                .ok_or_else(|| JsValue::from_str("Move: parent is not an element"))?;

            // Insert at the target position with Chawathe displacement
            insert_at_position(doc, parent_el, &node, target_idx, *detach_to_slot, slots)?;
        }
    }

    Ok(())
}

/// Insert a node at a position within a parent, using Chawathe displacement semantics.
/// If there's a node at the position, it gets replaced (and optionally stored in a slot).
fn insert_at_position(
    doc: &Document,
    parent: &Element,
    node: &Node,
    position: usize,
    detach_to_slot: Option<u32>,
    slots: &mut Slots,
) -> Result<(), JsValue> {
    let children = parent.child_nodes();
    let current_len = children.length() as usize;
    let pos = position as u32;

    trace!(
        parent_tag = parent.tag_name(),
        position,
        current_len,
        ?detach_to_slot,
        "insert_at_position"
    );

    if position < current_len {
        // Position exists - replace (Chawathe semantics - no shift)
        let existing = children.item(pos).unwrap();
        trace!(
            existing_node_type = existing.node_type(),
            existing_text = ?existing.text_content(),
            "replacing existing node"
        );
        let replaced = parent.replace_child(node, &existing)?;
        if let Some(slot) = detach_to_slot {
            trace!(slot, "storing replaced node in slot");
            slots.store(slot, replaced);
        }
    } else {
        // Position is beyond current children - grow with empty text placeholders
        trace!(
            growing_from = current_len,
            growing_to = position,
            "growing with placeholders"
        );
        for _ in current_len..position {
            let placeholder = doc.create_text_node("");
            parent.append_child(&placeholder)?;
        }
        parent.append_child(node)?;
    }

    Ok(())
}

/// Create a DOM node from InsertContent.
fn create_insert_content(doc: &Document, content: &InsertContent) -> Result<Node, JsValue> {
    match content {
        InsertContent::Element {
            tag,
            attrs,
            children,
        } => {
            let el = doc.create_element(tag)?;
            for attr in attrs {
                // Convert QualName to attribute name string
                let attr_name = if let Some(ref prefix) = attr.name.prefix {
                    format!("{}:{}", prefix, attr.name.local)
                } else {
                    attr.name.local.to_string()
                };
                el.set_attribute(&attr_name, &attr.value)?;
            }
            for child in children {
                let child_node = create_insert_content(doc, child)?;
                el.append_child(&child_node)?;
            }
            Ok(el.into())
        }
        InsertContent::Text(text) => Ok(doc.create_text_node(text).into()),
        InsertContent::Comment(text) => Ok(doc.create_comment(text).into()),
    }
}

/// Navigate a relative path within a node (for slot-relative paths).
fn navigate_within_node(root: &Node, path: &NodePath) -> Result<Node, JsValue> {
    let mut current = root.clone();
    for &idx in &path.0 {
        let children = current.child_nodes();
        current = children
            .item(idx as u32)
            .ok_or_else(|| JsValue::from_str(&format!("relative path child {} not found", idx)))?;
    }
    Ok(current)
}

/// Find a node by slot-based path.
/// Path format: [slot, child1, child2, ...] where slot 0 = body
fn find_node(doc: &Document, path: &NodePath, slots: &Slots) -> Result<Node, JsValue> {
    if path.0.is_empty() {
        return Err(JsValue::from_str("empty path"));
    }

    let slot = path.0[0] as u32;
    trace!(?path, slot, "find_node");

    // Get the slot root
    let slot_root: Node = if slot == 0 {
        doc.body()
            .ok_or_else(|| JsValue::from_str("no body"))?
            .into()
    } else {
        slots
            .get(slot)
            .ok_or_else(|| JsValue::from_str(&format!("slot {} not found", slot)))?
            .clone()
    };

    // Navigate within the slot root
    let mut current = slot_root;
    for &idx in &path.0[1..] {
        let children = current.child_nodes();
        let num_children = children.length();
        trace!(idx, num_children, "navigating to child");
        current = children.item(idx as u32).ok_or_else(|| {
            JsValue::from_str(&format!(
                "child {} not found (parent has {} children)",
                idx, num_children
            ))
        })?;
        trace!(
            node_type = current.node_type(),
            node_name = current.node_name(),
            "found node"
        );
    }

    Ok(current)
}

/// Find an element by DOM path.
fn find_element(doc: &Document, path: &NodePath, slots: &Slots) -> Result<Element, JsValue> {
    let node = find_node(doc, path, slots)?;
    node.dyn_into::<Element>()
        .map_err(|_| JsValue::from_str("node is not an element"))
}

/// Log a message to the browser console.
#[wasm_bindgen]
pub fn log(msg: &str) {
    web_sys::console::log_1(&JsValue::from_str(msg));
}

/// Get the innerHTML of the body element.
#[wasm_bindgen]
pub fn get_body_inner_html() -> Result<String, JsValue> {
    let window = web_sys::window().ok_or_else(|| JsValue::from_str("no window"))?;
    let document = window
        .document()
        .ok_or_else(|| JsValue::from_str("no document"))?;
    let body = document
        .body()
        .ok_or_else(|| JsValue::from_str("no body"))?;

    Ok(body.inner_html())
}

/// Set the innerHTML of the body element.
#[wasm_bindgen]
pub fn set_body_inner_html(html: &str) -> Result<(), JsValue> {
    let window = web_sys::window().ok_or_else(|| JsValue::from_str("no window"))?;
    let document = window
        .document()
        .ok_or_else(|| JsValue::from_str("no document"))?;
    let body = document
        .body()
        .ok_or_else(|| JsValue::from_str("no body"))?;

    body.set_inner_html(html);
    Ok(())
}

/// Dump the browser DOM structure as a string (for debugging).
#[wasm_bindgen]
pub fn dump_browser_dom() -> Result<String, JsValue> {
    let window = web_sys::window().ok_or_else(|| JsValue::from_str("no window"))?;
    let document = window
        .document()
        .ok_or_else(|| JsValue::from_str("no document"))?;
    let body = document
        .body()
        .ok_or_else(|| JsValue::from_str("no body"))?;

    fn dump_node(node: &Node, indent: usize) -> String {
        let prefix = "  ".repeat(indent);
        let mut result = String::new();

        let node_type = node.node_type();
        match node_type {
            Node::ELEMENT_NODE => {
                let tag = node.node_name();
                result.push_str(&format!("{}Element({})\n", prefix, tag));
            }
            Node::TEXT_NODE => {
                let text = node.text_content().unwrap_or_default();
                let escaped = text.replace('\n', "\\n").replace(' ', "·");
                result.push_str(&format!("{}Text({:?})\n", prefix, escaped));
            }
            _ => {
                result.push_str(&format!("{}Node(type={})\n", prefix, node_type));
            }
        }

        let children = node.child_nodes();
        for i in 0..children.length() {
            if let Some(child) = children.get(i) {
                result.push_str(&dump_node(&child, indent + 1));
            }
        }
        result
    }

    Ok(dump_node(&body.into(), 0))
}

/// Dump the Rust-parsed HTML structure as a string (for debugging).
/// Uses arena_dom which is what diff_html uses.
#[wasm_bindgen]
pub fn dump_rust_parsed(html: &str) -> Result<String, JsValue> {
    use hotmeal::{self, NodeKind};

    let full_html = format!("<html><body>{}</body></html>", html);
    let doc = parse(&full_html);

    fn dump_node(doc: &hotmeal::Document, node_id: NodeId, indent: usize) -> String {
        let prefix = "  ".repeat(indent);
        let node = doc.get(node_id);
        let mut result = match &node.kind {
            NodeKind::Document => format!("{}Document\n", prefix),
            NodeKind::Element(elem) => {
                format!("{}Element({})\n", prefix, elem.tag.as_ref().to_uppercase())
            }
            NodeKind::Text(t) => {
                let escaped = t.as_ref().replace('\n', "\\n").replace(' ', "·");
                format!("{}Text({:?})\n", prefix, escaped)
            }
            NodeKind::Comment(c) => {
                format!("{}Comment({:?})\n", prefix, c.as_ref())
            }
        };
        for child_id in node_id.children(&doc.arena) {
            result.push_str(&dump_node(doc, child_id, indent + 1));
        }
        result
    }

    // Find the body element to match the browser DOM dump behavior
    fn find_body(doc: &hotmeal::Document, node_id: NodeId) -> Option<NodeId> {
        let node = doc.get(node_id);
        if let NodeKind::Element(elem) = &node.kind
            && elem.tag.as_ref().eq_ignore_ascii_case("body")
        {
            return Some(node_id);
        }
        for child_id in node_id.children(&doc.arena) {
            if let Some(body_id) = find_body(doc, child_id) {
                return Some(body_id);
            }
        }
        None
    }

    let body_id = find_body(&doc, doc.root)
        .ok_or_else(|| JsValue::from_str("body element not found in parsed HTML"))?;

    Ok(dump_node(&doc, body_id, 0))
}
